# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1080460af8c65d4d7eac564c3d66feba592637038332b5ac24c1fd4ec183b05d0b03b4433207d937ea5c4ae240ec19ba4d9a7450e8eb7ad83e7e2eb3c43f1c8

test:
  secret_key_base: e6534dc1fb29cce138bfc5b9ef17ba30e7d364af7eff7856155ca9a7640b94e87e06267f1763e82b9f9bebb29aeaf0e7caa21464adc534a81121528f12d9a25d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
